domain: chz100p.github.io
analytics_id: ''
base_url: /Pinout.xyz/pinout/
resource_url: /Pinout.xyz/resources/
url_suffix:
urls:
  GND: ground
featured:
- scorezero
- motozero
- adafruit-arcade-bonnet
- sixfab-xbee-shield
